export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const SAVE_AND_DONE_TASK = "SAVE_AND_DONE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const REVERT_TASK = "REVERT_TASK";
export const SET_NUM_OF_VISIBLE_TASKS = "SET_NUM_OF_VISIBLE_TASKS";
export const SET_SEARCHED_TASKS = "SET_SEARCHED_TASKS";
